arm64: disable flatpak for now
Image builds are failing:

+ 23:08:30 INFO eibflatpak: Updating metadata for remote eos-runtimes
(process:17110): flatpak-DEBUG: 23:08:30.229: Fetching summary file for remote ���eos-runtimes���
+ 23:08:30 WARNING eib: Retrying attempt 1
Traceback (most recent call last):
  File "/tmp/image-build-SedAXvYBc1/lib/eib.py", line 351, in retry
    return func(*args, **kwargs)
gi.repository.GLib.GError: g-io-error-quark: GPG verification enabled, but no summary found (check that the configured URL in remote config is correct) (1)

eos-apps fails in the same way. Presumably this is because we haven't built
those repositories for arm64.

https://phabricator.endlessm.com/T27755