Fail build if Flatpaks are marked eol-rebase
Example output:

    + 13:25:17 WARNING eibflatpak: app/com.github.lainsce.notejot/x86_64/stable in flathub is marked as EOL: The application has been renamed to Notejot (io.github.lainsce.Notejot)
    + 13:25:17 WARNING eibflatpak: runtime/org.gnome.Platform/x86_64/3.28 in flathub is marked as EOL: The GNOME 3.28 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported platform.
    + 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform/x86_64/19.08 in flathub is marked as EOL: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
    + 13:25:17 WARNING eibflatpak: runtime/com.github.lainsce.notejot.Locale/x86_64/stable in flathub is marked as EOL: The application has been renamed to Notejot (io.github.lainsce.Notejot)
    + 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 in flathub is marked as EOL: The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.
    + 13:25:17 WARNING eibflatpak: runtime/org.gnome.Platform.Locale/x86_64/3.28 in flathub is marked as EOL: The GNOME 3.28 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported platform.
    + 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform.GL.default/x86_64/19.08 in flathub is marked as EOL: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
    + 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform.Locale/x86_64/19.08 in flathub is marked as EOL: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
    + 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/19.08 in flathub is marked as EOL: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
    + 13:25:17 ERROR eibflatpak: app/com.github.lainsce.notejot/x86_64/stable in flathub is marked as EOL, superseded by app/io.github.lainsce.Notejot/x86_64/stable
    + 13:25:17 ERROR eibflatpak: runtime/com.github.lainsce.notejot.Locale/x86_64/stable in flathub is marked as EOL, superseded by runtime/io.github.lainsce.Notejot.Locale/x86_64/stable
    Traceback (most recent call last):
      File "/sysroot/home/wjt/src/endlessm/eos-image-builder/run-build", line 611, in <module>
        main()
      File "/sysroot/home/wjt/src/endlessm/eos-image-builder/run-build", line 608, in main
        builder.run()
      File "/sysroot/home/wjt/src/endlessm/eos-image-builder/run-build", line 556, in run
        applist.show_apps(self.config,
      File "/sysroot/home/wjt/src/endlessm/eos-image-builder/lib/applist.py", line 268, in show_apps
        manager.resolve_refs()
      File "/sysroot/home/wjt/src/endlessm/eos-image-builder/lib/eibflatpak.py", line 868, in resolve_refs
        raise FlatpakError(
    eibflatpak.FlatpakError: Refusing to build image with eol-rebase refs: app/com.github.lainsce.notejot/x86_64/stable, runtime/com.github.lainsce.notejot.Locale/x86_64/stable

In a perfect world we would also fail the build if anything is marked
EOL, without replacement. However this is not practical for a few
reasons:

1. Several of our first-party apps use EOLed runtimes
2. All of our first-party runtimes drag in EOLed extensions because they
   are based on EOLed runtimes
3. There may be cases where we want to knowingly include an EOLed app

By contrast, if an app is marked eol-rebase, we can quickly update the
configuration to point to its new name: the same substitution will be
made by regular Flatpak app updates anyway. Making the build fail is the
simplest fway to make us make this change. We take care to batch up all
the changes that need to be made before failing so that the luckless
release engineer does not need to play whack-a-mole, one app at a time.

https://phabricator.endlessm.com/T28037
(cherry picked from commit 7504034b3eb07a34e1fdbedc8d31f9ddea7c1e4c)