Handle missing Flatpaks gracefully
Previously, if a listed Flatpak app or runtime is not present in that
remote, remote.match() would return None, but the calling code would
assume it is not None. This leads to a failure like this:

    + 20:16:29 INFO eibflatpak: Looking for app ref "com.orama_interactive.Pixelorama" match in flathub
    + 20:16:29 INFO eibflatpak: Removing repo option core.xa.languages
    + 20:16:29 INFO eibflatpak: Removing repo option core.xa.extra-languages
    + 20:16:29 INFO eibflatpak: Removing repo option core.xa.masked
    Traceback (most recent call last):
      File "/tmp/image-build-IZAJlTeyep/eos-image-builder/hooks/content/50-flatpak", line 61, in <module>
        manager.pull()
      File "/tmp/image-build-IZAJlTeyep/eos-image-builder/lib/eibflatpak.py", line 837, in pull
        txn = self._new_transaction()
      File "/tmp/image-build-IZAJlTeyep/eos-image-builder/lib/eibflatpak.py", line 808, in _new_transaction
        self._add_installs(txn)
      File "/tmp/image-build-IZAJlTeyep/eos-image-builder/lib/eibflatpak.py", line 799, in _add_installs
        logger.info('Adding app %s from %s', ref.ref, remote.name)
    AttributeError: 'NoneType' object has no attribute 'ref'

Handle this gracefully, collecting all errors in case more than one
Flatpak is missing, then fail at the end.

https://phabricator.endlessm.com/T34603