defaults: Install Snapshot instead of Cheese
EOL Cheese blocks EOS image build with error:

ERROR eibflatpak: app/org.gnome.Cheese/x86_64/stable in flathub is marked as EOL, superseded by app/org.gnome.Snapshot/x86_64/stable
Traceback (most recent call last):
  File "/tmp/image-build-BND0SeN7tG/eos-image-builder/lib/eibflatpak.py", line 844, in _on_pull_txn_ready
    self._check_excluded_operations(operations)
  File "/tmp/image-build-BND0SeN7tG/eos-image-builder/lib/eibflatpak.py", line 790, in _check_excluded_operations
    raise FlatpakError(
eibflatpak.FlatpakError: Refs marked eol-rebase in resolved flatpaks: runtime/org.gnome.Cheese.Locale/x86_64/stable, app/org.gnome.Cheese/x86_64/stable

Cheese on Flathub has commit ("Use end-of-life-rebase to point the new
app") [1] pointing to the successor org.gnome.Snapshot. So, install
Snapshot instead of Cheese.

[1]: https://github.com/flathub/org.gnome.Cheese/commit/d10253868bef9bbb70a68cdef1cd3df1166d5343
https://app.asana.com/1/1203676861188277/project/1211949321657103/task/1212563165452290