error: Delete in progress published directories
If the build errors during publishing, then the server will have both
the .inprogress file as well as some partially transferred files. Since
we don't know the status of the transferred files, leaving them there is
basically useless and the entire directory should be deleted.

Delete any publishing directories that have .inprogress files on error.
Since the error stage doesn't know the current personality, iterate
through all personalities looking for in progress publishing dirs.

[endlessm/eos-shell#6026]